global:
  marketplace-ami: false
  owner: mongche.lee@gmail.com
  qsname: aws-molpadia
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true

tests:
  molpadia-streaming-taskcat-ci-test:
    parameter_input: taskcat-input-parameters.json
    template_file: streaming-media-master.yml
    regions:
      - ap-northeast-1
