name: Build a CI/CD pipeline that deploys AWS CloudFormation templates
on:
  push:
    branches:
      - develop
jobs:
  cloudformation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        name: Checkout the repository
      - uses: aws-actions/configure-aws-credentials@v1
        name: Configure AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - uses: aws-actions/aws-cloudformation-github-deploy@v1
        name: Deploy AWS CloudFormation nested stacks
        with:
          name: streaming-media-webapp-prod
          template: templates/streaming-media-master.yml
          capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_IAM
          parameter-overrides: Environment=prod,GitHubUser=molpadia,GitHubRepoName=component-streaming-media-webapp,GitHubOAuthToken=${{ secrets.OAUTH_TOKEN }},ReleaseBranch=master,SourceRepoBranch=develop,S3BucketName=${{ secrets.AWS_S3_BUCKET }}
