name: Build a CI/CD pipeline that deploys AWS CloudFormation templates
on:
  push:
    branches:
      - develop
jobs:
  cloudformation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout remote repository
        uses: actions/checkout@v2.1.0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Synchronize CloudFormation templates to remote S3 Bucket
        env:
          ACCEPTED_FILE_PATTERN: '*.yml'
          AWS_REGION: ap-northeast-1
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        run: |
          aws s3 cp templates s3://${AWS_S3_BUCKET}/component-streaming-media-webapp/templates --recursive --include ${ACCEPTED_FILE_PATTERN} --region ${AWS_REGION}
      - name: Deploy AWS CloudFormation nested stacks
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: streaming-media-webapp-prod
          template: templates/streaming-media-master.yml
          capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_IAM
          parameter-overrides: Environment=prod,GitHubUser=molpadia,GitHubRepoName=component-streaming-media-webapp,GitHubOAuthToken=${{ secrets.OAUTH_TOKEN }},ReleaseBranch=master,SourceRepoBranch=develop,S3BucketName=${{ secrets.AWS_S3_BUCKET }}
